# Generated by Django 6.1.1 on 2026-09-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_genre_platform_remove_game_platforms_game_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
